/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Satoshi', 'Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Satoshi', 'Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        // Design guideline scale: 12, 14, 16, 20, 24
        'ds-sm': ['12px', { lineHeight: '18px' }],
        'ds-base': ['14px', { lineHeight: '21px' }],
        'ds-lg': ['16px', { lineHeight: '24px' }],
        'ds-xl': ['20px', { lineHeight: '28px' }],
        'ds-2xl': ['24px', { lineHeight: '32px' }],
      },
      spacing: {
        'ds-xs': '4px',
        'ds-sm': '8px',
        'ds-md': '12px',
        'ds-lg': '16px',
        'ds-xl': '24px',
        'ds-2xl': '32px',
        'ds-3xl': '48px',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'ds-sm': '6px',
        'ds-md': '12px',
        'ds-lg': '20px',
        'ds-pill': '999px',
      },
      colors: {
        // Shadcn mapping
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        // PostRecaller brand — direct tokens for design fidelity.
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'surface-secondary': 'rgb(var(--surface-secondary) / <alpha-value>)',
        'on-surface-secondary': 'rgb(var(--on-surface-secondary) / <alpha-value>)',
        'surface-tertiary': 'rgb(var(--surface-tertiary) / <alpha-value>)',
        'on-surface-tertiary': 'rgb(var(--on-surface-tertiary) / <alpha-value>)',
        'surface-inverse': 'rgb(var(--surface-inverse) / <alpha-value>)',
        'on-surface-inverse': 'rgb(var(--on-surface-inverse) / <alpha-value>)',
        brand: 'rgb(var(--brand) / <alpha-value>)',
        'on-brand': 'rgb(var(--on-brand) / <alpha-value>)',
        'brand-secondary': 'rgb(var(--brand-secondary) / <alpha-value>)',
        'on-brand-secondary': 'rgb(var(--on-brand-secondary) / <alpha-value>)',
        'brand-tertiary': 'rgb(var(--brand-tertiary) / <alpha-value>)',
        'on-brand-tertiary': 'rgb(var(--on-brand-tertiary) / <alpha-value>)',
        'ds-border': 'rgb(var(--ds-border) / <alpha-value>)',
        'ds-border-strong': 'rgb(var(--ds-border-strong) / <alpha-value>)',
        'ds-error': 'rgb(var(--ds-error) / <alpha-value>)',
        'ds-warning': 'rgb(var(--ds-warning) / <alpha-value>)',
        'ds-success': 'rgb(var(--ds-success) / <alpha-value>)',
      },
      boxShadow: {
        'tier-1': '0 1px 2px rgba(28, 28, 26, 0.04), 0 2px 8px rgba(28, 28, 26, 0.06)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'shimmer': { '0%': { backgroundPosition: '-800px 0' }, '100%': { backgroundPosition: '800px 0' } },
        'fade-in-up': { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'shimmer': 'shimmer 1.6s linear infinite',
        'fade-in-up': 'fade-in-up 0.5s ease-out both',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
